#b#cff0000ffWhat is Rainbow Race?#nb#nc
The Rainbow Race is a weekly event that all players can participate in.
\nApplications are accepted from:
12:00AM to 8:00PM (UTC) every Saturday.
\nThe game starts every Saturday at 9:00PM and ends at 11:00 PM UTC
\nThe Rainbow Race consists of 7 mini-games that take place all over Madrigal. The speed of your flying vehicle, general skill, and luck are the most important elements to winning the race.