#b#cffffdd66 Rainbow Race Registration #nb#nc 
- Application Fee: 1,000,000 Penya 
- Who can apply: All players 
- What you'll need: Any flying vehicle 
- When to apply: 12:00AM ~ 8:00PM on every Saturday 
- Race start: Every Saturday 9:00 PM 
- Race ends: At 11:00 PM
- Rewards: 
1st place: 50% of all application fees 
2nd place: 24% of all application fees 
3rd place: 12% of all application fees 
4th place: 6% of all application fees 
5th place: 3% of all application fees 
6th place: 1.5% of all application fees 
7th~10th: Less than 1.5% of all application fees 

* Please get your flying vehicle ready before the race starts, it is your responsibility to have it prepared ahead of time. 
* If you decide to cancel you application, the application fee will not be returned.