#b#cff0000ff Mix Costume #nb#nc
Register 3 to 5 costumes in the slot, then press the Start button. You can receive any one of the following costumes.

#b#cff0000ff Acquisition List #nb#nc
Almighty Dragon Set #nb#nc
Fierce Dragon Set #nb#nc
Wise Dragon Set #nb#nc
Blue Sailor (M) Set #nb#nc
Red Sailor (M) Set #nb#nc
Red Sailor (F) Set #nb#nc
Indigo Sailor (F) Set #nb#nc
Cats Set #nb#nc
Uniform (M) Set #nb#nc
Pink Nurse (F) Set #nb#nc
Giraffe Set #nb#nc
Shinigami Set #nb#nc
Amphibian Warrior Set #nb#nc